services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - TZ=America/New_York
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - jisoonet 

volumes:
  grafana:
    name: grafana

networks:
  jisoonet:
    name: jisoonet