services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    environment:
      TZ: "America/New_York"
    ports:
      - "9080:9080"
      - "9443:9443"
      - "9022:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-log:/var/log/gitlab
    networks:
      - jisoonet

volumes:
  gitlab-config:
    name: gitlab-config
  gitlab-data:
    name: gitlab-data
  gitlab-log:
    name: gitlab-log

networks:
  jisoonet:
    name: jisoonet

