services:
  excoffierleonard.com:
    image: git.jisoonet.com/el/excoffierleonard.com
    container_name: excoffierleonard.com
    ports:
      - "8080:80"
      - "4343:443"
    volumes:
      - ./ssl:/ssl
      - /mnt/zmain/repo:/var/www/html/repo
