version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - TZ=America/New_York
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama:/root/.ollama
    networks:
      - jisoonet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - TZ=America/New_York
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "28080:8080"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - jisoonet
    depends_on:
      - ollama

volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui

networks:
  jisoonet:
    name: jisoonet