services:
  leogpt:
    image: git.jisoonet.com/el/discordgpt
    container_name: leogpt
    environment:
      TZ: "America/New_York"
    volumes:
      - leogpt:/discordgpt/config
    networks:
      - jisoonet

volumes:
  leogpt:
    name: leogpt

networks:
  jisoonet:
    name: jisoonet