services:
  mariadb-mondo_db:
    image: mariadb
    container_name: mariadb-mondo_db
    environment:
      - TZ=America/New_York
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - mariadb-mondo_db:/var/lib/mysql
    networks:
      - jisoonet

volumes:
  mariadb-mondo_db:
    name: mariadb-mondo_db

networks:
  jisoonet:
    name: jisoonet