services:
  backgroundremover:
    image: git.jisoonet.com/el/backgroundremover
    container_name: backgroundremover
    environment:
      - TZ=America/New_York
    ports:
      - '5124:5124'
    networks:
      - jisoonet

networks:
  jisoonet:
    name: jisoonet